version: 2
jobs:
  test_net35:
    docker:
      - image: mono:latest
    working_directory: ~/workspace-net35
    steps:
      - checkout
      - run: apt-get update -yy && apt-get install -yy make git
      - run: make setup-net
      - run: make test-net35

  test_net45:
    docker:
      - image: mono:latest
    working_directory: ~/workspace-net45
    steps:
      - checkout
      - run: apt-get update -yy && apt-get install -yy make git
      - run: make setup-net
      - run: make test-net45

  test_netcoreapp2_0:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    working_directory: ~/workspace-netcoreapp2_0
    steps:
      - checkout
      - run: apt-get update -yy && apt-get install -yy make git
      - run: make setup
      - run: make test-netcore20

  coverage:
    docker:
      - image: microsoft/dotnet:2.2-sdk
    working_directory: ~/workspace-netcoreapp2_0
    steps:
      - checkout
      - run:
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
          when: always
      - run: mkdir coverage
      - run: dotnet restore VJson.standalone/VJson.Editor.Tests/VJson.Editor.Tests.csproj
      - run: dotnet build VJson.standalone/VJson.Editor.Tests/VJson.Editor.Tests.csproj -f netcoreapp2.0
      - run: dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=lcov /p:CoverletOutput='./lcov.info' VJson.standalone/VJson.Editor.Tests/VJson.Editor.Tests.csproj -f netcoreapp2.0
      - run: cp VJson.standalone/VJson.Editor.Tests/lcov.info coverage/.
      - run: ./cc-test-reporter after-build -t lcov

workflows:
  version: 2
  commit:
    jobs:
      - test_net35
      - test_net45
      - test_netcoreapp2_0
      - coverage
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test_net35
      - test_net45
      - test_netcoreapp2_0
